#pragma once
#include <string>
#include <map>
#include <memory>

#include "Common/Geommath/2D/Math.hpp"

// Lazer
#define WEAPON_LAZER_ORIGIN_HIEGHT RAND_I(450,550)
#define WEAPON_LAZER_DAM_BASE 2.5f
#define WEAPON_LAZER_FIRE_PERIOD 0.5
#define WEAPON_LAZER_BULLET_SPEED 800.0f
#define WEAPON_LAZER_BULLE_DAM_BASE 15.0f

// Kinetic Gun
#define WEAPON_KINETICGUN_FIRE_PERIOD 0.1
#define WEAPON_KINETICGUN_BULLET_SPEED 800.0f
#define WEAPON_KINETICGUN_DAM_BASE 7.5f
#define WEAPON_KINETICGUN_SPREAD 3.14159265359f / 8.0f
#define WEAPON_KINETICGUN_EXPLOSION_LIFETIME 0.1

// Missile
#define WEAPON_MISSILE_FIRE_PERIOD 0.5
#define WEAPON_MISSILE_BULLET_ACC 800.0f
#define WEAPON_MISSILE_DAM_BASE 15.0f
#define WEAPON_MISSILE_EXPLOSION_LIFETIME 0.2

// UFO
#define UFO_ROT_SPEED PI 
#define UFO_SPEED_1  200.0f
#define UFO_SPEED_2  400.0f
#define UFO_SPEED_3  600.0f

#define UFO_FIRE_MODE_1_FIRE_PERIOD .5f
#define UFO_FIRE_MODE_2_FIRE_PERIOD 1.0f
#define UFO_FIRE_MODE_3_FIRE_PERIOD .25f
#define UFO_BULLET_BASE_DAMAGE 25.0f

namespace My
{
	enum class WEAPON_TYPE
	{
		WEAPON_MISSILE = 0,
		WEAPON_LAZER,
		WEAPON_KINETICGUN,	

		WEAPON_KINETICGUN_BULLET,
		WEAPON_MISSILE_BULLET,

		WEAPON_MISSILE_EXPLOSION,
		WEAPON_KINETICGUN_EXPLOSION,

		WEAPON_LAZER_BEAM,

		UFO_BULLET,

		NUM
	};
}

